import { DEMO_PORTFOLIOS, INVESTOR_PROFILES, MACRO_EVENTS, refreshQuotes } from './data.js';
import { addPosition, flattenPositions, getPortfolios, getVisiblePortfolios, initStore, money, pct, savePortfolios, setSelectedAccount, state, subscribe, totals, updatePosition, KEYS } from './store.js';
import { allocationBars, depositsBar, donutAccounts, projectionLine, sparkline } from './charts.js';
import { closeNotificationPanel, evaluateAlerts, openNotificationPanel, renderNotificationPanel, requestNotificationPermission } from './notifications.js';

const routes = { '/': 'dashboard', dashboard: 'dashboard', analyse: 'analyse', signaux: 'signaux', inventaire: 'inventaire' };
const pageFile = route => `./pages/${route}.html`;
const app = document.getElementById('app-content');
const fmtDate = value => new Date(value).toLocaleDateString('fr-FR');
const perf = p => (p.currentPrice - p.pru) / p.pru * 100;
const valueOf = p => p.qty * p.currentPrice;
const investedOf = p => p.qty * p.pru;
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

initStore(DEMO_PORTFOLIOS);
applyDarkMode();
requestNotificationPermission();
setupShell();
subscribe(() => { populateAccounts(); renderNotificationPanel(); });
window.addEventListener('hashchange', loadRoute);
loadRoute();
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');

function setupShell() {
  populateAccounts();
  document.getElementById('account-select').addEventListener('change', event => setSelectedAccount(event.target.value));
  document.getElementById('dark-toggle').addEventListener('click', toggleDarkMode);
  document.getElementById('notification-toggle').addEventListener('click', openNotificationPanel);
  document.getElementById('notification-close').addEventListener('click', closeNotificationPanel);
  renderNotificationPanel();
}
function populateAccounts() {
  const select = document.getElementById('account-select');
  select.innerHTML = `<option value="global">Compte global</option>${getPortfolios().map(p => `<option value="${p.id}">${p.name}</option>`).join('')}`;
  select.value = state.selectedAccount;
}
function applyDarkMode() {
  const enabled = localStorage.getItem(KEYS.darkMode) === 'true';
  document.documentElement.classList.toggle('dark', enabled);
  document.getElementById('dark-toggle')?.querySelector('.material-symbols-outlined')?.replaceChildren(document.createTextNode(enabled ? 'light_mode' : 'dark_mode'));
}
function toggleDarkMode() { localStorage.setItem(KEYS.darkMode, String(!document.documentElement.classList.contains('dark'))); applyDarkMode(); }
async function loadRoute() {
  const key = location.hash.replace(/^#\/?/, '') || 'dashboard';
  const route = routes[key] || 'dashboard';
  app.innerHTML = '<div class="glass-card card-pad rounded-xl">Chargement…</div>';
  try { app.innerHTML = await (await fetch(pageFile(route))).text(); } catch { app.innerHTML = '<div class="glass-card card-pad rounded-xl">Page indisponible hors ligne.</div>'; }
  document.querySelectorAll('[data-route]').forEach(link => link.classList.toggle('active', link.dataset.route === route));
  app.focus({ preventScroll: true });
  ({ dashboard: renderDashboard, analyse: renderAnalyse, signaux: renderSignaux, inventaire: renderInventaire }[route])();
}

function renderDashboard() {
  const accounts = getVisiblePortfolios(); const all = getPortfolios(); const t = totals(accounts); const peaMax = 150000; const peaLeft = Math.max(0, peaMax - t.peaVersements);
  const top = [...t.positions].sort((a,b) => perf(b) - perf(a)).slice(0,5);
  const nearStops = t.positions.filter(p => (p.currentPrice - p.stopLevel) / p.currentPrice * 100 < 3);
  document.getElementById('dashboard-grid').innerHTML = `
    <article class="glass-card metric-card card-pad md:col-span-7"><p class="label-caps text-secondary">Solde Total Global</p><div id="total-count" class="headline-lg data-tabular mt-3">${money(0)}</div><p class="mt-2 font-bold ${t.gain >= 0 ? 'text-secondary' : 'text-error'}">${t.gain >= 0 ? '+' : ''}${money(t.gain)} · ${pct(t.perf)} · 24h estimé ${(t.perf/180).toFixed(2)}%</p></article>
    <article class="glass-card card-pad md:col-span-5"><p class="label-caps text-secondary">Plafond PEA</p><div class="mt-4 flex justify-between"><strong>${money(t.peaVersements)}</strong><span>/ ${money(peaMax)}</span></div><div class="progress mt-3"><span style="width:${Math.min(100,t.peaVersements/peaMax*100)}%"></span></div><p class="body-sm mt-3">Reste disponible: <strong>${money(peaLeft)}</strong></p></article>
    <article class="glass-card card-pad md:col-span-5"><h2 class="headline-md">Répartition des comptes</h2><canvas id="accounts-donut" class="mt-4" aria-label="Graphique donut de répartition"></canvas></article>
    <article class="glass-card card-pad md:col-span-7"><h2 class="headline-md">Actifs les plus performants</h2><div class="mt-4 space-y-3">${top.map(p => positionRow(p)).join('')}</div></article>
    <article class="glass-card card-pad md:col-span-4"><h2 class="headline-md">Résumé Performance</h2><dl class="mt-4 grid grid-cols-2 gap-3">${[['YTD',t.perf*.62],['1 mois',t.perf*.08],['1 an',t.perf],['TRI global',t.perf*.75]].map(([k,v]) => `<div class="rounded-xl bg-white/60 p-3 dark:bg-slate-900"><dt class="label-caps text-muted">${k}</dt><dd class="text-2xl font-extrabold data-tabular ${v>=0?'text-secondary':'text-error'}">${pct(v)}</dd></div>`).join('')}</dl></article>
    <article class="glass-card card-pad md:col-span-8 ${nearStops.length ? 'border-error/70 bg-red-50/70 dark:bg-red-950/30' : ''}"><h2 class="headline-md">Alertes contextuelles</h2><div class="mt-4 space-y-3">${nearStops.length ? nearStops.map(p => `<p class="font-bold text-error"><span class="material-symbols-outlined">warning</span> ${p.ticker} proche du stop (${money(p.stopLevel)})</p>`).join('') : '<p class="body-sm text-muted">Aucun stop suiveur à moins de 3% du seuil.</p>'}</div></article>`;
  countUp('total-count', t.value); donutAccounts('accounts-donut', all, account => { setSelectedAccount(account.id); loadRoute(); });
  document.getElementById('refresh-quotes').addEventListener('click', async e => { e.currentTarget.disabled = true; e.currentTarget.innerHTML = 'Actualisation…'; await refreshQuotes(); evaluateAlerts(getPortfolios()); renderDashboard(); });
}
function positionRow(p) { return `<div class="flex items-center justify-between gap-3 rounded-xl border border-outline-variant bg-white/60 p-3 dark:border-slate-700 dark:bg-slate-900"><div><div class="flex items-center gap-2"><strong>${p.ticker}</strong><span class="pill ${p.accountType==='PEA'?'pill-pea':'pill-cto'}">${p.accountType}</span></div><p class="body-sm text-muted dark:text-slate-300">${p.isin} · ${esc(p.name)}</p></div><div class="text-right"><p class="font-extrabold data-tabular">${money(valueOf(p))}</p><p class="font-bold ${perf(p)>=0?'text-secondary':'text-error'}">${pct(perf(p))}</p></div></div>`; }
function countUp(id, end) { const el = document.getElementById(id); let start; const step = ts => { start ??= ts; const p = Math.min(1, (ts-start)/800); el.textContent = money(end*p); if (p<1) requestAnimationFrame(step); }; requestAnimationFrame(step); }

function allocation() {
  const t = totals(); const classes = ['Actions','Obligations','Liquidités','Crypto']; const by = Object.fromEntries(classes.map(c => [c,0]));
  t.positions.forEach(p => by[p.assetClass || 'Actions'] = (by[p.assetClass || 'Actions'] || 0) + valueOf(p));
  return { labels: classes, current: classes.map(c => t.value ? (by[c]||0)/t.value*100 : 0), total: t.value };
}
function renderAnalyse() {
  const select = document.getElementById('profile-select'); select.innerHTML = Object.entries(INVESTOR_PROFILES).map(([id,p]) => `<option value="${id}">${p.label} — ${p.objective}</option>`).join(''); select.value = sessionStorage.getItem('alphaTerm_profile') || 'dynamique';
  const draw = () => { sessionStorage.setItem('alphaTerm_profile', select.value); const profile = INVESTOR_PROFILES[select.value]; const a = allocation(); const target = a.labels.map(l => profile.target[l] || 0); const deltas = a.current.map((v,i) => Math.abs(v-target[i])); const score = Math.max(0, 100 - deltas.reduce((s,v)=>s+v,0)); const badge = score>85?'OPTIMAL':score>=70?'BON':score>=50?'À REVOIR':'CRITIQUE';
    document.getElementById('analysis-grid').innerHTML = `<article class="glass-card card-pad md:col-span-4"><p class="label-caps text-secondary">Score de cohérence</p><div class="headline-lg data-tabular mt-3">${Math.round(score)}</div><span class="pill mt-2 ${score>70?'pill-pea':'bg-red-100 text-error'}">${badge}</span><p class="body-sm mt-4">${profile.label}: objectif ${profile.objective}, horizon ${profile.horizon}.</p></article><article class="glass-card card-pad md:col-span-8"><h2 class="headline-md">Allocation vs cible</h2><canvas id="allocation-chart" class="mt-4"></canvas></article><article class="glass-card card-pad md:col-span-6"><h2 class="headline-md">Stratégie de rééquilibrage</h2><div class="mt-4 space-y-3">${rebalance(a, target, profile).join('')}</div></article><article class="glass-card card-pad md:col-span-6"><h2 class="headline-md">Conseils d'investissement</h2><div class="mt-4 grid gap-3">${advice(profile).join('')}</div></article><article class="glass-card card-pad md:col-span-12"><h2 class="headline-md">Simulation objectif</h2><form id="sim-form" class="mt-4 grid gap-3 md:grid-cols-4"><input class="input" name="initial" type="number" value="${Math.round(a.total)}" aria-label="Montant initial"><input class="input" name="monthly" type="number" value="700" aria-label="Versement mensuel"><input class="input" name="years" type="number" value="8" aria-label="Horizon années"><input class="input" name="rate" type="number" step="0.01" value="${profile.rate}" aria-label="Taux cible"></form><canvas id="projection-chart" class="mt-4"></canvas></article>`;
    allocationBars('allocation-chart', a.labels, a.current, target, a.total); setupProjection(); };
  select.addEventListener('change', draw); draw();
}
function rebalance(a, target, profile) { return a.labels.map((l,i) => { const delta = a.current[i]-target[i]; const amount = Math.abs(delta)/100*a.total; if (amount < 500) return `<p class="body-sm">${l}: alignement satisfaisant.</p>`; return `<div class="rounded-xl border border-outline-variant p-3 dark:border-slate-700"><strong>${delta>0?'VENDRE':'ACHETER'} ${money(amount)}</strong><p class="body-sm">${delta>0?'Alléger les actifs les plus performants, PEA avant CTO pour limiter la fiscalité.':'Renforcer '+profile.etf+'.'}</p></div>`; }); }
function advice(profile) { const positions = flattenPositions().sort((a,b)=>perf(b)-perf(a)); const peaLeft = 150000 - totals(getPortfolios().filter(p=>p.type==='PEA')).peaVersements; return [`<div class="rounded-xl border border-outline-variant p-3 dark:border-slate-700"><strong>DCAM · ${money(Math.min(1500, peaLeft))}</strong><p class="body-sm">Renfort cœur MSCI World adapté au profil ${profile.label} et à l'espace PEA restant.</p><button class="btn-secondary mt-2 order-btn" data-ticker="DCAM">Ajouter au panier d'ordres</button></div>`, ...positions.filter(p => (p.currentPrice-p.stopLevel)/p.currentPrice*100 < 6 || perf(p)<0).slice(0,2).map(p => `<div class="rounded-xl border border-outline-variant p-3 dark:border-slate-700"><strong>Arbitrer ${p.ticker}</strong><p class="body-sm">Stop proche, surpondération ou performance négative à surveiller.</p></div>` )]; }
function setupProjection() { const form = document.getElementById('sim-form'); const draw = () => { const fd = new FormData(form); const initial=+fd.get('initial'), monthly=+fd.get('monthly'), years=+fd.get('years'), rate=+fd.get('rate'); const labels=[], med=[], opt=[], pes=[]; for(let y=0;y<=years;y++){ labels.push(`${y} an`); const compound = (r)=> initial*Math.pow(1+r,y)+monthly*12*((Math.pow(1+r,y)-1)/(r||.0001)); med.push(compound(rate)); opt.push(compound(rate*1.25)); pes.push(compound(rate*.65)); } projectionLine('projection-chart', labels, med, opt, pes); }; form.addEventListener('input', draw); draw(); }

function indicators(values) { const closes = values?.length ? values : Array.from({length:220}, (_,i)=>100+i*.18+Math.sin(i/7)*4); const diffs = closes.slice(1).map((v,i)=>v-closes[i]); const gains = diffs.slice(-14).filter(v=>v>0).reduce((s,v)=>s+v,0)/14; const losses = Math.abs(diffs.slice(-14).filter(v=>v<0).reduce((s,v)=>s+v,0))/14 || .01; const rsi = 100 - 100/(1+gains/losses); const avg = n => closes.slice(-n).reduce((s,v)=>s+v,0)/Math.min(n,closes.length); const mm50=avg(50), mm200=avg(200); const atr = Math.abs(closes.at(-1)-closes.at(-15))/14 || 2.5; const mean=avg(20), sd=Math.sqrt(closes.slice(-20).reduce((s,v)=>s+(v-mean)**2,0)/20); return { rsi, rsiLabel: rsi<30?'Survendu':rsi<45?'Refroidissement':rsi<55?'Neutre':rsi<70?'Surchauffe':'Suracheté', macd: closes.at(-1)>avg(26)?'Croisement Haussier':'Croisement Baissier', ma: mm50>mm200?'Croix d’Or':'Tendance Stable', atr, boll: closes.at(-1)>mean+2*sd?'Bande haute':closes.at(-1)<mean-2*sd?'Bande basse':'Canal central' }; }
function renderSignaux() { const positions = flattenPositions(); const signals = positions.map(p => ({ ...p, ...indicators(p.history?.closes) })); evaluateAlerts(getVisiblePortfolios(), signals); document.getElementById('signals-layout').innerHTML = `<div class="space-y-6"><section class="glass-card card-pad"><h2 class="headline-md">Alertes temps réel</h2><div class="mt-4 space-y-3">${state.alerts.slice(0,4).map(a=>`<div class="rounded-xl border border-outline-variant p-3 dark:border-slate-700"><strong>${a.title}</strong><p class="body-sm">${a.message}</p></div>`).join('') || '<p>Aucune alerte.</p>'}</div></section><section class="glass-card card-pad"><h2 class="headline-md">Signaux techniques</h2><div class="mt-4 grid gap-3">${signals.map(s=>`<article class="rounded-xl border border-outline-variant p-3 dark:border-slate-700"><div class="flex justify-between gap-3"><div><strong>${s.ticker}</strong><p class="body-sm">RSI ${s.rsi.toFixed(1)} · ${s.rsiLabel}</p></div><span class="pill ${s.rsi>70?'bg-red-100 text-error':'pill-pea'}">${s.rsi<30?'ACHAT FORT':s.rsi<45?'ACHAT':s.rsi<55?'CONSERVER':s.rsi<70?'SURVEILLER':'VENTE'}</span></div><dl class="mt-3 grid grid-cols-2 gap-2 body-sm"><div>MACD: <b>${s.macd}</b></div><div>MM: <b>${s.ma}</b></div><div>ATR(14): <b>${s.atr.toFixed(2)}</b></div><div>Bollinger: <b>${s.boll}</b></div><div>Stop suggéré: <b>${money(s.pru+3*s.atr)}</b></div><div>Impact géopolitique: <b>${macroImpact(s)}</b></div></dl><canvas id="spark-${s.ticker}" height="45"></canvas></article>`).join('')}</div></section></div><aside class="space-y-4"><section class="glass-card card-pad"><h2 class="headline-md">Macro / Géopolitique</h2><div class="mt-4 space-y-3">${MACRO_EVENTS.map(e=>`<article class="rounded-xl border border-outline-variant p-3 dark:border-slate-700"><div class="flex justify-between"><strong>${e.title}</strong><span class="pill ${e.sentiment==='Négatif'?'bg-red-100 text-error':'pill-pea'}">${e.sentiment}</span></div><p class="body-sm mt-2">${e.summary}</p><p class="label-caps mt-2 text-muted">${e.tags.join(' · ')}</p></article>`).join('')}</div></section></aside>`; signals.forEach(s => sparkline(`spark-${s.ticker}`, s.history?.closes?.slice(-40) || Array.from({length:40}, (_,i)=>s.currentPrice + Math.sin(i/4)*2 + i*.05))); document.getElementById('export-report').addEventListener('click', () => window.print()); }
function macroImpact(p) { const score = MACRO_EVENTS.reduce((s,e)=>s+(e.impact[p.sector]||0),0); return score>0?'Positif':score<0?'Négatif':'Neutre'; }

function renderInventaire() { const root = document.getElementById('inventory-root'); const accounts = getPortfolios(); let filter = 'all', q = '', sort = 'value';
  const draw = () => { const allT = totals(getVisiblePortfolios()); let rows = flattenPositions(filter==='all'?getVisiblePortfolios():accounts.filter(a=>a.id===filter)).filter(p => [p.ticker,p.name,p.isin].join(' ').toLowerCase().includes(q)); rows.sort((a,b)=> sort==='gains'?(valueOf(b)-investedOf(b))-(valueOf(a)-investedOf(a)):sort==='weight'?valueOf(b)/allT.value-valueOf(a)/allT.value:sort==='perf'?perf(b)-perf(a):valueOf(b)-valueOf(a)); root.innerHTML = `<div class="glass-card card-pad"><div class="flex flex-wrap gap-2">${['all',...accounts.map(a=>a.id)].map(id=>`<button class="btn-secondary tab" data-id="${id}">${id==='all'?'Tous':accounts.find(a=>a.id===id).name}</button>`).join('')}</div><div class="mt-4 grid gap-3 md:grid-cols-2"><input id="search" class="input" placeholder="Rechercher ticker, nom, ISIN" value="${esc(q)}"><select id="sort" class="input"><option value="value">Tri par valeur</option><option value="gains">Tri par gains</option><option value="weight">Tri par poids</option><option value="perf">Tri par performance %</option></select></div></div><div class="grid gap-4 md:grid-cols-2">${rows.map(p=>positionCard(p, allT.value)).join('')}</div>${depositsSection(accounts)}`; document.getElementById('sort').value=sort; document.querySelectorAll('.tab').forEach(b=>{ b.classList.toggle('bg-primary', b.dataset.id===filter); b.addEventListener('click',()=>{filter=b.dataset.id;draw();});}); document.getElementById('search').addEventListener('input',e=>{q=e.target.value.toLowerCase();draw();}); document.getElementById('sort').addEventListener('change',e=>{sort=e.target.value;draw();}); document.querySelectorAll('.edit-stop').forEach(b=>b.addEventListener('click',()=>openPositionModal(b.dataset.account,b.dataset.ticker))); document.getElementById('export-csv').addEventListener('click', exportCSV); depositsBar('deposits-chart', depositLabels(accounts), depositCumul(accounts), 150000); };
  document.getElementById('add-position').addEventListener('click',()=>openPositionModal()); draw(); }
function positionCard(p,total){ const gain=valueOf(p)-investedOf(p), dist=(p.currentPrice-p.stopLevel)/p.currentPrice*100; return `<article class="glass-card card-pad"><div class="flex justify-between gap-3"><div><div class="flex items-center gap-2"><h3 class="text-2xl font-extrabold">${p.ticker}</h3><span class="pill ${p.accountType==='PEA'?'pill-pea':'pill-cto'}">${p.accountType}</span></div><p class="body-sm text-muted">${p.name} · ${p.isin}</p></div><span class="pill ${perf(p)>=0?'pill-pea':'bg-red-100 text-error'}"><span class="material-symbols-outlined">${perf(p)>=0?'trending_up':'trending_down'}</span>${pct(perf(p))}</span></div><dl class="mt-4 grid grid-cols-2 gap-3"><div><dt class="label-caps text-muted">Valeur actuelle</dt><dd class="font-extrabold">${money(valueOf(p))}</dd></div><div><dt class="label-caps text-muted">Investi</dt><dd>${money(investedOf(p))}</dd></div><div><dt class="label-caps text-muted">Gains/Pertes</dt><dd class="font-bold ${gain>=0?'text-secondary':'text-error'}">${money(gain)}</dd></div><div><dt class="label-caps text-muted">Poids</dt><dd>${pct(valueOf(p)/total*100)}</dd></div></dl><div class="mt-4 rounded-xl border border-outline-variant p-3 dark:border-slate-700"><strong class="${dist<3?'text-error':''}">Stop Suiveur: ${money(p.stopLevel)} · distance ${pct(dist)}</strong></div><button class="btn-secondary edit-stop mt-4" data-account="${p.accountId}" data-ticker="${p.ticker}">Éditer stop</button></article>`; }
function depositsSection(accounts){ const deposits=accounts.flatMap(a=>(a.deposits||[]).map(d=>({...d, account:a.name}))).sort((a,b)=>new Date(b.date)-new Date(a.date)); return `<section class="glass-card card-pad"><div class="flex justify-between gap-3"><h2 class="headline-md">Versements</h2><button id="export-csv" class="btn-secondary">Export CSV</button></div><p class="mt-2 body-sm">Prochain versement suggéré: Dans 24 jours, verser 700€ pour optimiser DCA.</p><canvas id="deposits-chart" class="mt-4"></canvas><div class="mt-4 space-y-2">${deposits.map(d=>`<div class="flex justify-between rounded-xl bg-white/60 p-3 dark:bg-slate-900"><span>${fmtDate(d.date)} · ${d.account}</span><strong>${money(d.amount)}</strong></div>`).join('')}</div></section>`; }
function depositLabels(accounts){ return [...new Set(accounts.flatMap(a=>(a.deposits||[]).map(d=>d.date.slice(0,7))))].sort(); }
function depositCumul(accounts){ let sum=0; return depositLabels(accounts).map(m=>{ sum += accounts.flatMap(a=>a.deposits||[]).filter(d=>d.date.startsWith(m)).reduce((s,d)=>s+d.amount,0); return sum; }); }
function openPositionModal(accountId, ticker){ const editing=accountId&&ticker; const pos=editing?flattenPositions(getPortfolios()).find(p=>p.accountId===accountId&&p.ticker===ticker):{}; const modal=document.createElement('div'); modal.className='modal-backdrop'; modal.innerHTML=`<form class="glass-card card-pad w-full max-w-xl rounded-xl"><h2 class="headline-md">${editing?'Éditer stop':'Ajouter position'}</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><input class="input" name="ticker" required placeholder="Ticker" value="${esc(pos.ticker||'')}"><input class="input" name="isin" required placeholder="ISIN" value="${esc(pos.isin||'')}"><input class="input md:col-span-2" name="name" required placeholder="Nom" value="${esc(pos.name||'')}"><input class="input" name="qty" type="number" step="0.01" required placeholder="Quantité" value="${pos.qty||''}"><input class="input" name="pru" type="number" step="0.01" required placeholder="PRU" value="${pos.pru||''}"><input class="input" name="currentPrice" type="number" step="0.01" required placeholder="Cours" value="${pos.currentPrice||''}"><input class="input" name="stopLevel" type="number" step="0.01" required placeholder="Stop Level" value="${pos.stopLevel||''}"><select class="input" name="account">${getPortfolios().map(a=>`<option value="${a.id}" ${a.id===(accountId||'jean-pea')?'selected':''}>${a.name}</option>`).join('')}</select></div><div class="mt-4 flex justify-end gap-2"><button type="button" class="btn-secondary cancel">Annuler</button><button class="btn-primary">Sauvegarder</button></div></form>`; document.body.append(modal); modal.querySelector('.cancel').addEventListener('click',()=>modal.remove()); modal.querySelector('form').addEventListener('submit',e=>{ e.preventDefault(); const fd=new FormData(e.currentTarget); const data={ticker:fd.get('ticker').toUpperCase(),isin:fd.get('isin'),name:fd.get('name'),assetClass:'Actions',sector:'World',qty:+fd.get('qty'),pru:+fd.get('pru'),currentPrice:+fd.get('currentPrice'),stopLevel:+fd.get('stopLevel'),lastUpdate:new Date().toISOString()}; editing?updatePosition(accountId,ticker,data):addPosition(fd.get('account'),data); modal.remove(); renderInventaire(); }); }
function exportCSV(){ const rows=[['Compte','Ticker','ISIN','Nom','Quantité','PRU','Cours','Stop'],...flattenPositions().map(p=>[p.accountName,p.ticker,p.isin,p.name,p.qty,p.pru,p.currentPrice,p.stopLevel])]; const blob=new Blob([rows.map(r=>r.join(';')).join('\n')],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='alphaterminal-inventaire.csv'; a.click(); URL.revokeObjectURL(a.href); }
